# Generated by Django 2.2.16 on 2020-09-11 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mute',
            name='mute_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 1, 41, 29, 681945), verbose_name='Время Мута'),
        ),
    ]
