# Generated by Django 2.2.16 on 2020-09-11 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20200912_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.IntegerField(default=0, verbose_name='ИД Сообщения'),
        ),
        migrations.AlterField(
            model_name='mute',
            name='mute_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 1, 42, 18, 939583), verbose_name='Время Мута'),
        ),
    ]
