# Generated by Django 2.2.16 on 2020-09-11 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20200912_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mute',
            name='mute_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 1, 42, 38, 673517), verbose_name='Время Мута'),
        ),
        migrations.AlterField(
            model_name='user',
            name='discord_id',
            field=models.IntegerField(unique=True, verbose_name='Дискорд ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='steam_id',
            field=models.IntegerField(unique=True, verbose_name='Стим ID'),
        ),
    ]
