# Generated by Django 2.2.16 on 2020-09-11 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20200912_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mute',
            name='channel_id',
            field=models.IntegerField(verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='mute',
            name='mute_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 1, 42, 55, 649666), verbose_name='Время Мута'),
        ),
    ]
