# Generated by Django 2.2.16 on 2020-09-11 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20200912_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='leave_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 2, 32, 36, 503680), verbose_name='Время Окончания Абуза'),
        ),
        migrations.AlterField(
            model_name='mute',
            name='mute_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 2, 32, 36, 503680), verbose_name='Время Мута'),
        ),
    ]
