# Generated by Django 2.2.16 on 2020-09-11 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20200912_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.IntegerField(default=0, help_text='ID сообщения для нужного типа', verbose_name='ID Сообщения'),
        ),
        migrations.AlterField(
            model_name='mute',
            name='mute_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 2, 47, 15, 106544), verbose_name='Время Мута'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='leave_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 2, 47, 15, 106544), verbose_name='Время Окончания Абуза'),
        ),
    ]
