# Generated by Django 2.2.16 on 2020-09-12 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20200912_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mute',
            name='mute_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 12, 21, 4, 451359), verbose_name='Время Мута'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='leave_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 12, 21, 4, 451359), verbose_name='Время Кика из Очереди'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата Присоединения'),
        ),
    ]
