# Generated by Django 2.2.16 on 2020-09-12 09:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20200912_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(blank=True, choices=[('1', 'Queue Message'), ('2', 'Party Message'), ('3', 'Voice Message')], default='', help_text='Тип Сообщения', max_length=1, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='mute',
            name='channel_id',
            field=models.BigIntegerField(help_text='Канал Сообщения', verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='mute',
            name='mute_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 12, 49, 11, 348034), help_text='Время Мута', verbose_name='Время Мута'),
        ),
        migrations.AlterField(
            model_name='mute',
            name='user',
            field=models.ForeignKey(help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, to='bot.User', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='leave_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 15, 12, 49, 11, 348034), help_text='Время Кика из Очереди', verbose_name='Время Кика из Очереди'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='user',
            field=models.ForeignKey(help_text='Пользователь', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue_user', to='bot.User', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата Присоединения на Сервер', verbose_name='Дата Присоединения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='discord_id',
            field=models.BigIntegerField(help_text='Дискорд ID Пользователя', unique=True, verbose_name='Дискорд ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.BigIntegerField(default=0, help_text='Опыт Пользователя', verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=0, help_text='Уровень Пользователя', verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rep',
            field=models.PositiveIntegerField(default=0, help_text='Репутация Пользователя', verbose_name='Репутация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_steam_id',
            field=models.BigIntegerField(blank=True, default=0, help_text='Резервный Стим ID Пользователя', verbose_name='Второй Стим ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='steam_id',
            field=models.BigIntegerField(help_text='Стим ID Пользователя', unique=True, verbose_name='Стим ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(help_text='Имя Пользователя', max_length=50, verbose_name='Пользователь'),
        ),
    ]
