# Generated by Django 2.2.16 on 2020-09-12 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_auto_20200912_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mute',
            name='mute_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 12, 49, 13, 128979), help_text='Время Мута', verbose_name='Время Мута'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='leave_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 15, 12, 49, 13, 128979), help_text='Время Кика из Очереди', verbose_name='Время Кика из Очереди'),
        ),
    ]
