# Generated by Django 2.2.16 on 2020-09-12 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_auto_20200912_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mute',
            name='mute_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 0, 8, 46, 176141), help_text='Время Мута', verbose_name='Время Мута'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='leave_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 16, 0, 8, 46, 176141), help_text='Время Кика из Очереди', verbose_name='Время Кика из Очереди'),
        ),
        migrations.AlterField(
            model_name='user',
            name='discord_id',
            field=models.BigIntegerField(blank=True, help_text='Дискорд ID Пользователя', null=True, unique=True, verbose_name='Дискорд ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(help_text='Имя Пользователя', max_length=100, verbose_name='Пользователь'),
        ),
    ]
