# Generated by Django 2.2.16 on 2020-09-13 13:51

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_auto_20200913_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'ordering': ['id'], 'verbose_name': 'Системная Настройка', 'verbose_name_plural': 'Системные Настройки'},
        ),
        migrations.AlterField(
            model_name='mute',
            name='mute_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 16, 51, 3, 711343), help_text='Время Мута', verbose_name='Время Мута'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='leave_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 16, 16, 51, 3, 710343), help_text='Время Кика из Очереди', verbose_name='Время Кика из Очереди'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='value',
            field=ckeditor.fields.RichTextField(default='', max_length=2048, verbose_name='Значение'),
        ),
    ]
