# Generated by Django 2.2.16 on 2020-09-13 13:58

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_auto_20200913_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=25, verbose_name='Ключ')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Заголовок')),
                ('value', ckeditor.fields.RichTextField(default='', max_length=2048, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Системная Настройка',
                'verbose_name_plural': 'Системные Настройки',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.AlterField(
            model_name='mute',
            name='mute_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 16, 58, 1, 394137), help_text='Время Мута', verbose_name='Время Мута'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='leave_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 16, 16, 58, 1, 394137), help_text='Время Кика из Очереди', verbose_name='Время Кика из Очереди'),
        ),
    ]
