# Generated by Django 2.2.16 on 2020-09-13 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_auto_20200913_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeds',
            name='color',
            field=models.CharField(default=16254938, max_length=10, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='mute',
            name='mute_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 17, 5, 41, 639403), help_text='Время Мута', verbose_name='Время Мута'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='leave_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 16, 17, 5, 41, 638397), help_text='Время Кика из Очереди', verbose_name='Время Кика из Очереди'),
        ),
    ]
