# Generated by Django 2.2.16 on 2020-09-13 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_auto_20200913_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeds',
            name='color',
            field=models.IntegerField(default=16254938, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='mute',
            name='mute_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 17, 33, 27, 402300), help_text='Время Мута', verbose_name='Время Мута'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='leave_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 16, 17, 33, 27, 401312), help_text='Время Кика из Очереди', verbose_name='Время Кика из Очереди'),
        ),
    ]
