# Generated by Django 2.2.16 on 2020-09-13 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_auto_20200913_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeds',
            name='value',
            field=models.TextField(default='', max_length=2048, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='mute',
            name='mute_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 17, 38, 6, 36905), help_text='Время Мута', verbose_name='Время Мута'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='leave_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 16, 17, 38, 6, 36905), help_text='Время Кика из Очереди', verbose_name='Время Кика из Очереди'),
        ),
    ]
