# Generated by Django 2.2.16 on 2020-09-13 19:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_auto_20200913_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mute',
            name='mute_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 22, 42, 32, 928117), help_text='Время Мута', verbose_name='Время Мута'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='leave_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 16, 19, 42, 32, 927156, tzinfo=utc), help_text='Время Кика из Очереди', verbose_name='Время Кика из Очереди'),
        ),
    ]
