# Generated by Django 2.2.16 on 2020-09-14 19:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0027_auto_20200914_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeds',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='mute',
            name='mute_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 15, 19, 53, 46, 71353, tzinfo=utc), help_text='Время Мута', verbose_name='Время Мута'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='leave_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 19, 53, 46, 70355, tzinfo=utc), help_text='Время Кика из Очереди', verbose_name='Время Кика из Очереди'),
        ),
    ]
