# Generated by Django 2.2.16 on 2020-09-16 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0029_auto_20200914_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='leave_time',
        ),
        migrations.AlterField(
            model_name='mute',
            name='mute_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 13, 7, 45, 147039, tzinfo=utc), help_text='Время Мута', verbose_name='Время Мута'),
        ),
    ]
