# Generated by Django 2.2.16 on 2020-09-16 17:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0030_auto_20200916_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mute',
            name='mute_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 17, 32, 58, 330519, tzinfo=utc), help_text='Время Мута', verbose_name='Время Мута'),
        ),
    ]
