# Generated by Django 2.2.16 on 2020-09-17 10:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0031_auto_20200916_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='LvlSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=20, verbose_name='Ключ')),
                ('value', models.IntegerField(default=5, help_text='Опыт, который получает пользователь', verbose_name='К-во опыта')),
            ],
            options={
                'verbose_name': 'Система опыта',
                'verbose_name_plural': 'Системы опыта',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='mute',
            name='mute_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 10, 13, 35, 195622, tzinfo=utc), help_text='Время Мута', verbose_name='Время Мута'),
        ),
    ]
