# Generated by Django 2.2.16 on 2020-09-17 10:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0032_auto_20200917_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mute',
            name='mute_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 10, 45, 8, 25120, tzinfo=utc), help_text='Время Мута', verbose_name='Время Мута'),
        ),
        migrations.AlterField(
            model_name='mute',
            name='user',
            field=models.ForeignKey(help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='muted_user', to='bot.User', verbose_name='Пользователь'),
        ),
    ]
