# Generated by Django 2.2.16 on 2020-09-17 15:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0033_auto_20200917_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rep',
        ),
        migrations.AlterField(
            model_name='mute',
            name='mute_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 15, 41, 54, 217896, tzinfo=utc), help_text='Время Мута', verbose_name='Время Мута'),
        ),
    ]
