# Generated by Django 2.2.16 on 2020-09-17 16:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0034_auto_20200917_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered',
            field=models.BooleanField(default=False, verbose_name='Проверка на роль'),
        ),
        migrations.AlterField(
            model_name='mute',
            name='mute_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 16, 57, 59, 984113, tzinfo=utc), help_text='Время Мута', verbose_name='Время Мута'),
        ),
    ]
