# Generated by Django 2.2.16 on 2020-09-23 11:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0035_auto_20200917_1958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Embeds',
        ),
        migrations.AlterField(
            model_name='mute',
            name='mute_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 11, 12, 47, 839052, tzinfo=utc), help_text='Время Мута', verbose_name='Время Мута'),
        ),
    ]
